# Generated by Django 5.1.7 on 2025-03-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
